version: '3'
services:
  solr:
    image: "solr"
    entrypoint:
    - bash
    - "-c"
    - "precreate-core drugs; precreate-core diseases; precreate-core genetic; precreate-core covid; exec solr -f"
    ports:
     - "8983:8983"
